config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
  }
  
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  scope module: :publics do
    resources :items, only: [:index,:show]
    delete 'cart_items/destroy_all' =>'cart_items#destroy_all'
    resources :cart_items, only: [:index,:update,:destroy,:create]
    get 'orders/top' => 'orders#top'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new,:create,:index,:show]
    # post 'orders/confirm' => 'orders#confirm'
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
    get 'about' => 'homes#about'
    root 'homes#top'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/customers/infomation' => 'customers#update'
    get 'customers/withdrawal' =>'customers#withdrawal'
    get 'customers/confirm' => 'customers#confirm'
  end
  

  namespace :admins do
   resources :items, only: [:index, :show, :new, :create, :edit, :update]
   resources :genres, only: [:index,:create,:edit,:update]
   resources :customers, only: [:index,:show,:edit,:update]
   resources :order_details, only: [:update]
   resources :orders, only: [:show,:update]
   get 'top' => 'homes#top'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }
  
  validates :postal_code, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  validates :customer_id, presence: true
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def update
    @order_status = Order.find(params[:id])
    @order_status.update(order_params)
    redirect_to admins_order_path(@order_status)
  end
  
  def show
    @order = Order.find(params[:id])
    @details = @order.order_details
    @shipping_cost = 800
  end
  
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/publics/addresses_controller.rb
class Publics::AddressesController < ApplicationController
  def index
    @address = Address.new
    @addresses = current_customer.addresses
  end
  
  def edit
    @address = Address.find(params[:id])
    
  end
  
  def create
    @address = Address.new(address_params)
    @address.customer_id=current_customer.id
    @address.save
    redirect_to addresses_path
  end
  
  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end
  
  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path
  end
  
  
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email)
  end
  
  def address_params
    params.require(:address).permit(:name, :postal_code, :address,)
  end
end

app/controllers/publics/cart_items_controller.rb
class Publics::CartItemsController < ApplicationController
  def index
    @cart_item_all = current_customer.cart_items
    @price = 0
    #@cart_item = CartItem.find(params[:id])
   # @calculation = *1.1
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    if @cart_item.save
      redirect_to cart_items_path
    else
      @item = Item.find(@cart_item.item_id)
      # @cart_item = CartItem.new
      render 'publics/items/show'
    end
  end
  
  private
  
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :customer_id, :amount)
  end
  
  #def amount_params
    #params.repuire(:cart_item).permit(:amount)
  #end
end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/customers_controller.rb
class Publics::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = Customer.find(current_customer.id)
    @customer.update(customer_params)
    redirect_to customers_mypage_path( @customer)
  end

  def confirm
  end

  def withdrawal
    @customer_id = Customer.find(current_customer.id)
    @customer_id.is_active = false
    @customer_id.update
    redirect_to customers_confirm_path
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
    #     #例 Discographyテーブルの1番最初のレコードを取得
    # @discography = Discography.first
    
    # #例 Discographyテーブルの先頭から3件のレコードを取得
    # @discography = Discography.first(3)
    
    # #例 Discographyテーブルの1番末尾から4件のレコードを取得
    @new_item = Item.last(4)
  end
  def about
  end
  
end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController
  before_action :move_to_signed_in, except: [:index]
  def index
    @itemall = Item.all
  end
  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    #@cart_item.customer_id = current_customer.id
    #@cart_item.item_id = @item.id
  end
  
  private
  
  def move_to_signed_in
    unless customer_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/customers/sign_up'
    end
  end
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/orders_controller.rb
class Publics::OrdersController < ApplicationController
  
  def new
    @order = Order.new
    @customer_address = current_customer.address
    @customer_last_name = current_customer.last_name
    @customer_first_name = current_customer.first_name
  end
  
  def confirm
    #byebug
    @cart_item_all = current_customer.cart_items
    @order = Order.new(order_params)
    @order.shipping_cost = 800
    if params[:order][:select_address] == "0"
      #ご自身の住所を保存する処理
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name+current_customer.first_name
    elsif params[:order][:select_address] == "1"
      #登録済みの住所を保存する処理
      if params[:order][:address_id]
        order = Address.find(params[:order][:address_id])
        @order.postal_code = order.postal_code
        @order.address = order.address
        @order.name = order.name
      else
        flash.now[:danger] = "登録に失敗しました"
        render:new
      end
    elsif params[:order][:select_address] == "2"
      #新規登録住所
      # unless params[:order][:postal_code].blank?#<=本当は[order][:address, :postal_code, name]にしたい ＃追記blankが正しくてもすべて弾く
      # else
      #   render:new
      # end
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    else 
       @customer_last_name = current_customer.last_name
       @customer_first_name = current_customer.first_name
       flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  def top
  end
  
  def create
    #byebug
    @order = Order.new(order_params)
    @order.status = 0
    if @order.save
      @cart_items = current_customer.cart_items
      @cart_items.each do |cart_item|
        @order_detail = OrderDetail.new
        @order_detail.item_id = cart_item.item.id
        @order_detail.price = cart_item.item.with_tax_price
        @order_detail.amount = cart_item.amount
        @order_detail.order_id = @order.id
        @order_detail.save
      end
      @cart_items.destroy_all
      redirect_to orders_top_path
    else
      render:new
    end
  end
  
  def index
    @current_customer_orders = current_customer.orders.all
    #@order_details = order.order_details.new(3)
  end
  
  def show
    #byebug
    @order = Order.find(params[:id])
    @shipping_cost = 800
  end
  
  private
    def order_params
      params.require(:order).permit(:payment_method, :postal_code, :name, :address, :customer_id, :shipping_cost, :total_payment)
    end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end
  
  def after_sign_up_path_for(resource)
    customers_mypage_path
  end
  
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  def after_sign_in_path_for(resource)
   root_path
  end
  


  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/publics/addresses_helper.rb
module Publics::AddressesHelper
end

app/helpers/publics/cart_items_helper.rb
module Publics::CartItemsHelper
end

app/helpers/publics/customers_helper.rb
module Publics::CustomersHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/items_helper.rb
module Publics::ItemsHelper
end

app/views/publics/orders/confirm.html.erb
<div class="row mt-5">
  <div class="col-auto offset-1 bg-gray">
    <h4 class="mb-0">注文情報確認</h4>
  </div>
</div>
<%= form_with model: @order, url: orders_path, method: :POST, local:true do |f| %>
  <div class="row mt-5">
    <div class="col-9">
      <table class="table table-bordered border-dark">
        <thead>
          <tr class="bg-gray">
            <th class="col-4">商品名</th>
            <th class="col-2">単価(税込)</th>
            <th class="col-2">数量</th>
            <th class="col-2">小計</th>
            <!--<th class="col-2"></th>-->
          </tr>
        </thead>
        <tbody>
          <% @sum = 0 %>
          <% @cart_item_all.each do |cart_item| %>
            <tr>
              <td>
                <%= attachment_image_tag cart_item.item, :image, size: "30x20", format: 'jpeg' %>  <%= cart_item.item.name %>
              </td>
              <td><%= cart_item.item.with_tax_price %></td>
              <%#= form_with model: cart_item, url: cart_item_path(cart_item), method: :PATCH, local:true do |f| %>
                <td>
                  <div class="row">
                    <div class="col-auto my-auto">
                      <%#= f.select :amount, *[1..10], autocomplete: "f.amount", class: "form-select" %>
                      <%= cart_item.amount %>
                    </div>
                    <div class="col-auto">
                      <%#= f.submit "変更", class: "btn btn-success btn-block" %>
                    </div>
                  </div>
                </td>
              <%#end%>
              <td><%= cart_item.subtotal %></td>
              <!--<td>-->
              <!--  <div class="row">-->
              <!--    <div class="col-auto mx-auto">-->
                    <%#= link_to "削除する", cart_item_path(cart_item), method: :delete, class: " btn btn-danger btn-block my-auto" %>
              <!--    </div>-->
              <!--  </div>-->
              <!--</td>-->
            </tr>
            <% @sum += cart_item.subtotal %>
          <%end%>
        </tbody>
      </table>
    </div>
    <div class="col-3">
      <table class="table table-bordered border-dark">
        <tr>
          <th class="bg-gray">送料</th>
          <td><%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <th class="bg-gray">商品合計</th>
          <td><%= @sum %></td>
        </tr>
        <tr>
          <th class="bg-gray">請求金額</th>
          <td><%= @sum + @order.shipping_cost %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
      <h5>支払い方法</h5>
    </div>
    <div class="col">
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-2">
      <h5>お届け先</h5>
    </div>
    <div class="col">
      〒<%= @order.postal_code %><%= @order.address %>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col">
      <%= @order.name %>
    </div>
  </div>
  <%= f.hidden_field :payment_method, value: @order.payment_method %>
  <%= f.hidden_field :customer_id, value: current_customer.id %>
  <%= f.hidden_field :postal_code, value: @order.postal_code %>
  <%= f.hidden_field :address, value: @order.address %>
  <%= f.hidden_field :name, value: @order.name %>
  <%= f.hidden_field :total_payment, value: @sum + @order.shipping_cost %>
  <%= f.hidden_field :shipping_cost, value: @order.shipping_cost %>
  
  <div class="row mt-5">
    <div class="col-auto mx-auto">
      <%= f.submit "注文を確定する", class: "btn btn-success btn-block" %>
    </div>
  </div>
<%end%>

app/views/publics/orders/index.html.erb
<div class="row mt-5">
  <div class="col-auto offset-1 bg-gray">
    <h4 class="mb-0">注文履歴一覧</h4>
  </div>
</div>

<div class="row mt-5">
  <div class="col">
    <table class="table table-bordered border-dark">
      <thead>
        <tr>
          <th class="col-2">追加日</th>
          <th class="col-3">配送先</th>
          <th class="col-2">注文商品</th>
          <th class="col-1">支払金額</th>
          <th class="col-2">ステータス</th>
          <th class="col-2">注文詳細</th>
        </tr>
      </thead>
      <tbody>
        <% @current_customer_orders.each do |order| %>
            <tr>
              <td><%= l order.created_at, format: :short %></td>
              <td>
                <div><%= order.postal_code %></div>
                <div><%= order.address %></div>
                <div><%= order.name %></div>
              </td>
              <td>
                <% order.order_details.each do |detail| %>
                  <div><%= detail.item.name %></div>
                <%end%>
              </td>
              <td>
                <h6><%= order.total_payment %>円</h6>
              </td>
              <td><%= order.status_i18n %></td>
              <td><%= link_to "表示する", order_path(order), class: "btn btn-primary" %></td>
            </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/publics/orders/new.html.erb
<% if @order.errors.any? %>
  <%= @order.errors.count %>件のエラーが発生しました
  <% @order.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= flash[:danger] %>
<div class="row mt-5">
  <div class="col-auto offset-1">
    <h4 class="mb-0 bg-gray">注文情報入力</h4>
  </div>
</div>

<div class="row mt-5">
  <div class="col">
    <h5>支払い方法</h5>
  </div>
</div>
<%#= form_with model: cart_item, url: cart_item_path(cart_item), method: :PATCH, local:true do |f| %>
<%= form_with model: @order, url: orders_confirm_path, method: :POST, local:true do |f| %>
  <div class="row">
    <div class="col ml-5">
      <%= f.radio_button :payment_method, Order.payment_methods.key(0) %>
      <%= f.label :payment_method, Order.payment_methods_i18n[:credit_card] %>
      <%#= f.radio_button :payment_method, "credit_card" %>
      <%#= f.label :payment_method, "クレジットカード" %>
    </div>
  </div>
  <div class="row">
    <div class="col ml-5">
      <%#= f.radio_button :payment_method, "transfer" %>
      <%#= f.label :payment_method, "銀行振込" %> 
      <%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
      <%= f.label :payment_method, Order.payment_methods_i18n[:transfer]%>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col">
      <h5>お届け先</h5>
    </div>
  </div>
  
  <div class="row">
    <div class="col ml-5">
      <%= f.radio_button :select_address, "0" %>
      <%= f.label :select_address, "ご自身の住所" %> 
    </div>
  </div>
  <div class="row">
    <div class="col ml-5">
      <h6 class="ml-4">
        <%= @customer_address %>
      </h6>
    </div>
  </div>
  <div class="row">
    <div class="col ml-5">
      <h6 class="ml-4">
        <%= @customer_last_name %><%= @customer_first_name %>
      </h6>
    </div>
  </div>
  
  <div class="row">
    <div class="col ml-5">
      <%= f.radio_button :select_address, "1" %>
      <%= f.label :select_address, "登録済み住所から選択" %> 
    </div>
  </div>
  
  <div class="row">
    <div class="col ml-5">
      <h6 class="ml-4">
        <%= f.select :address_id, options_from_collection_for_select(current_customer.addresses.all, :id, :full_address) %>
      </h6>
    </div>
  </div>
  
  <div class="row mt-2">
    <div class="col ml-5">
      <%= f.radio_button :select_address, "2" %>
      <%= f.label :select_address, "新しいお届け先" %> 
    </div>
  </div>
  
  <div class="row mt-2">
    <div class="col-3 ml-5 my-auto">
      <h6 class="ml-4 my-auto">
        郵便番号(ハイフンなし)
      </h6>
    </div>
    <div class="col-3">
      <%= f.text_field :postal_code,class: "form-control" %>
      <%#= f.text_field :last_name,class: 'form-control',autofocus: true, autocomplete: "last_name" %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-3 ml-5 my-auto">
      <h6 class="ml-4 my-auto">
        住所
      </h6>
    </div>
    <div class="col-7">
      <%= f.text_field :address,class: "form-control" %>
      <%#= f.text_field :last_name,class: 'form-control',autofocus: true, autocomplete: "last_name" %>
    </div>
  </div>
  
  <div class="row mt-2">
    <div class="col-3 ml-5 my-auto">
      <h6 class="ml-4 my-auto">
        宛名
      </h6>
    </div>
    <div class="col-3">
      <%= f.text_field :name,class: "form-control" %>
      <%#= f.text_field :last_name,class: 'form-control',autofocus: true, autocomplete: "last_name" %>
    </div>
 </div>
  <%= f.submit %>
<%end%>

app/views/publics/orders/show.html.erb
<div class="row mt-5">
  <div class="col-auto offset-1 bg-gray">
    <h4 class="mb-0">注文履歴詳細</h4>
  </div>
</div>

<div class="row mt-5">
  <div class="col-8">
    <h5>注文情報</h5>
  </div>
  <div class="col-4">
    <h5>請求情報</h5>
  </div>
</div>

<div class="row mt-3">
  <div class="col-8">
    <table class="table table-bordered border-dark">
      <tr><th class="bg-gray">注文日</th><td><%= l @order.created_at, format: :short %></td></tr> 
      <tr>
        <th class="bg-gray">配送先</th>
        <td>
          <div><%= @order.postal_code %></div>
          <div><%= @order.address %></div>
          <div><%= @order.name %></div>
        </td>
      </tr>
      <tr><th class="bg-gray">支払方法</th><td><%= @order.payment_method_i18n %></td></tr>
      <tr><th class="bg-gray">ステータス</th><td><%= @order.status_i18n %></td></tr>
    </table>
  </div>
  <div class="col-4">
    <table class="table table-bordered border-dark">
      <tr><th class="bg-gray">商品合計</th><td><%= @order.total_payment-@shipping_cost %></td></tr>
      <tr><th class="bg-gray">配送料</th><td><%= @shipping_cost %></td></tr>
      <tr><th class="bg-gray">ご請求額</th><td><%= @order.total_payment %></td></tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col">
    <h5>注文内容</h5>
  </div>
</div>
<div class="row mt-3">
  <div class="col-9">
    <table class="table table-bordered border-dark">
      <thead>
        <tr class="bg-gray">
          <th class="col-8">商品</th><th class="col-2">単価(税込)</th><th class="col-1">個数</th><th class="col-1">小計</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_details.each do |detail| %>
          <tr><td><%= detail.item.name %></td><td><%= detail.item.with_tax_price %></td><td><%= detail.amount %></td><td><%= detail.item.with_tax_price*detail.amount %></td></tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/publics/orders/top.html.erb
<div class="row order_top">
  <div class="col-auto mx-auto my-auto">
    <h5>ご注文ありがとうございました。</h5>
  </div>
</div>