config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
  }
  
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  scope module: :publics do
    resources :items, only: [:index,:show]
    delete 'cart_items/destroy_all' =>'cart_items#destroy_all'
    resources :cart_items, only: [:index,:update,:destroy,:create]
    get 'orders/top' => 'orders#top'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new,:create,:index,:show]
    # post 'orders/confirm' => 'orders#confirm'
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
    get 'about' => 'homes#about'
    root 'homes#top'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/customers/infomation' => 'customers#update'
    get 'customers/withdrawal' =>'customers#withdrawal'
    get 'customers/confirm' => 'customers#confirm'
  end
  

  namespace :admins do
   resources :items, only: [:index, :show, :new, :create, :edit, :update]
   resources :genres, only: [:index,:create,:edit,:update]
   resources :customers, only: [:index,:show,:edit,:update]
   resources :order_details, only: [:update]
   resources :orders, only: [:show,:update]
   get 'top' => 'homes#top'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * amount
  end
  validates :amount, presence: true,
                     length: { minimum: 1, maximum: 10 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :orders
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  def with_tax_price
    (price * 1.1).floor
  end
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price,numericality: { only_integer: true }
  validates :genre_id, presence: true
  # validates :is_active, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }
  
  validates :postal_code, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  validates :customer_id, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, in_production: 2, production_completed: 3 }
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @order_all = Order.all
    
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  def index
    @itemp= Item.page(params[:page]).per(3)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      render:new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item)
    else
      render:edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encryted_password, :telephone_number, :postal_code, :address])
  end
  
  
  # def after_sign_in_path_for(resource)
  # top_path
  # end
  
  # def after_sign_up_path_for(resource)
  #   customer_path
  # end
end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController
  before_action :move_to_signed_in, except: [:index]
  def index
    @itemall = Item.all
  end
  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    #@cart_item.customer_id = current_customer.id
    #@cart_item.item_id = @item.id
  end
  
  private
  
  def move_to_signed_in
    unless customer_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/customers/sign_up'
    end
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/addresses_helper.rb
module Publics::AddressesHelper
end

app/helpers/publics/cart_items_helper.rb
module Publics::CartItemsHelper
end

app/helpers/publics/customers_helper.rb
module Publics::CustomersHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/items_helper.rb
module Publics::ItemsHelper
end

app/helpers/publics/orders_helper.rb
module Publics::OrdersHelper
end

app/views/admins/items/create.html.erb
<h1>Admins::Items#create</h1>
<p>Find me in app/views/admins/items/create.html.erb</p>

app/views/admins/items/edit.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <% @item.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="row mt-5">
  <div class="col-auto offset-1">
    <h4 class="mb-0 bg-gray">商品編集</h4>
  </div>
</div>
<%= form_with model: @item, url: admins_item_path(@item), method: :PATCH, local:true do |f| %>
    <div class="row mt-5">
      <div class="col-7 mx-auto">
        <div class="row">
          <div class="col-3 mt-auto mb-auto">
            商品画像
          </div>
          <div class="col-8">
            <%= f.attachment_field :image %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            商品名
          </div>
          <div class="col-8">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            商品説明
          </div>
          <div class="col-8">
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            ジャンル
          </div>
          <div class="col-8">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, class:"col-6" %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-2 mt-auto mb-auto">
            税抜価格
          </div>
          <div class="col-8 offset-1">
            <%= f.text_field :price, class: 'form-control' %>
          </div>
          <div class="col-auto mt-auto mb-auto">円</div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            販売ステータス
          </div>
          <div class="col-8">
            <div class="row">
              <div class="col-auto">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, "販売中" %>
              </div>
              <div class="col-auto">
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "販売停止中" %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-4 mx-auto mt-4">
          <%= f.submit "変更を保存" , class: "btn btn-success btn-block" %>
        </div>
      </div>
    </div>
<%end%>

app/views/admins/items/index.html.erb
<div class="row mt-5">
  <div class="col-auto offset-1">
    <div class="row bg-gray">
      <h4 class="mb-0 mx-auto col-auto">商品一覧</h4>
    </div>
  </div>
  <div class="col-auto ml-auto">
    <%= link_to new_admins_item_path do %>
      <i class="fas fa-plus-circle plus-button"></i>
    <%end%>
  </div>
</div>
<div class="row mt-5">
  <table class="table">
    <thead>
      <tr class="bg-gray">
        <th class="col-1">商品ID</th>
        <th class="col-3">商品名</th>
        <th class="col-1">税抜価格</th>
        <th class="col-3">ジャンル</th>
        <th class="col-2">ステータス</th>
      </tr>
    </thead>  
    <% @itemp.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td class="row">
          <%= link_to admins_item_path(item) do %>
            <h6 class="col-auto text-dark border-bottom border-dark"><%= item.name %></h6>
          <%end%>
        </td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <% if item.is_active == true then %>
          <td>
            <h6 class="text-success">販売中</h6>
          </td>
        <%else%>
          <td>
            <h6 class="text-black-50">販売停止中</h6>
          </td>
        <%end%>
      </tr>
    <%end%>
  </table>
</div>
<div class="row">
  <div class="col-auto mx-auto">
    <%= paginate @itemp %>
  </div>
</div>

app/views/admins/items/new.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <% @item.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="row mt-5">
  <div class="col-auto offset-1">
    <h4 class="mb-0 bg-gray">商品新規登録</h4>
  </div>
</div>
<%= form_with model: @item, url: admins_items_path(@item), method: :POST, local:true do |f| %>
    <div class="row mt-5">
      <div class="col-7 mx-auto">
        <div class="row">
          <div class="col-3 mt-auto mb-auto">
            商品画像
          </div>
          <div class="col-8">
            <%= f.attachment_field :image %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            商品名
          </div>
          <div class="col-8">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            商品説明
          </div>
          <div class="col-8">
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            ジャンル
          </div>
          <div class="col-8">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--", class:"col-6" %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-2 mt-auto mb-auto">
            税抜価格
          </div>
          <div class="col-8 offset-1">
            <%= f.text_field :price, class: 'form-control' %>
          </div>
          <div class="col-auto mt-auto mb-auto">円</div>
        </div>
        <div class="row mt-3">
          <div class="col-3 mt-auto mb-auto">
            販売ステータス
          </div>
          <div class="col-8">
            <div class="row">
              <div class="col-auto">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, "販売中" %>
              </div>
              <div class="col-auto">
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "販売停止中" %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-4 mx-auto mt-4">
          <%= f.submit "新規登録" , class: "btn btn-success btn-block" %>
        </div>
      </div>
    </div>
<%end%>

app/views/admins/items/show.html.erb
<div class="row mt-5">
  <div class="col-auto offset-1 bg-gray">
    <h4 class="mb-0">商品詳細</h4>
  </div>
</div>
<div class="row mt-5">
  <div class="col-auto">
   <%= attachment_image_tag @item, :image, size: "300x200", format: 'jpeg', fallback: "no_image.jpg" %>
  </div>
  <div class="col-6 ml-3">
    <div class="row">
      <div class="col-3">商品名</div>
      <div class="col-8"><h5><%= @item.name %></h5></div>
    </div>
    <div class="row mt-3">
      <div class="col-3">商品説明</div>
      <div class="col-8"><h5><%= @item.introduction %></h5></div>
    </div>
    <div class="row mt-3">
      <div class="col-3">ジャンル</div>
      <div class="col-8"><h5><%= @item.genre.name %></h5></div>
    </div>
    <div class="row mt-3">
      <div class="col-3">税込価格
        <div class="row-auto">
          (税抜価格)
        </div>
      </div>
      <div class="col-8 my-auto"><h5><%= @item.with_tax_price %>(<%= @item.price %>)円</h5></div>
    </div>
    <div class="row mt-4">
      <div class="col-3">販売ステータス</div>
      <div class="col-8">
        <% if @item.is_active == true then %>
          <h5 class="text-success">販売中</h6>
        <%else%>
          <h5 class="text-black-50">販売停止中</h5>
        <%end%> 
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-2 mx-auto mt-5">
    <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-success btn-block" %>
  </div>
</div>

app/views/admins/items/update.html.erb
<h1>Admins::Items#update</h1>
<p>Find me in app/views/admins/items/update.html.erb</p>