config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
  }
  
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  scope module: :publics do
    resources :items, only: [:index,:show]
    delete 'cart_items/destroy_all' =>'cart_items#destroy_all'
    resources :cart_items, only: [:index,:update,:destroy,:create]
    get 'orders/top' => 'orders#top'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new,:create,:index,:show]
    # post 'orders/confirm' => 'orders#confirm'
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
    get 'about' => 'homes#about'
    root 'homes#top'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/customers/infomation' => 'customers#update'
    get 'customers/withdrawal' =>'customers#withdrawal'
    get 'customers/confirm' => 'customers#confirm'
  end
  

  namespace :admins do
   resources :items, only: [:index, :show, :new, :create, :edit, :update]
   resources :genres, only: [:index,:create,:edit,:update]
   resources :customers, only: [:index,:show,:edit,:update]
   resources :order_details, only: [:update]
   resources :orders, only: [:show,:update]
   get 'top' => 'homes#top'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :orders
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
    @customerall = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
    else
      render:edit
    end
  end

  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/publics/addresses_controller.rb
class Publics::AddressesController < ApplicationController
  def index
    @address = Address.new
    @addresses = current_customer.addresses
  end
  
  def edit
    @address = Address.find(params[:id])
    
  end
  
  def create
    @address = Address.new(address_params)
    @address.customer_id=current_customer.id
    @address.save
    redirect_to addresses_path
  end
  
  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end
  
  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path
  end
  
  
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email)
  end
  
  def address_params
    params.require(:address).permit(:name, :postal_code, :address,)
  end
end

app/controllers/publics/cart_items_controller.rb
class Publics::CartItemsController < ApplicationController
  def index
    @cart_item_all = current_customer.cart_items
    @price = 0
    #@cart_item = CartItem.find(params[:id])
   # @calculation = *1.1
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    if @cart_item.save
      redirect_to cart_items_path
    else
      @item = Item.find(@cart_item.item_id)
      # @cart_item = CartItem.new
      render 'publics/items/show'
    end
  end
  
  private
  
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :customer_id, :amount)
  end
  
  #def amount_params
    #params.repuire(:cart_item).permit(:amount)
  #end
end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/customers_controller.rb
class Publics::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = Customer.find(current_customer.id)
    @customer.update(customer_params)
    redirect_to customers_mypage_path( @customer)
  end

  def confirm
  end

  def withdrawal
    @customer_id = Customer.find(current_customer.id)
    @customer_id.is_active = false
    @customer_id.update
    redirect_to customers_confirm_path
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
    #     #例 Discographyテーブルの1番最初のレコードを取得
    # @discography = Discography.first
    
    # #例 Discographyテーブルの先頭から3件のレコードを取得
    # @discography = Discography.first(3)
    
    # #例 Discographyテーブルの1番末尾から4件のレコードを取得
    @new_item = Item.last(4)
  end
  def about
  end
  
end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController
  before_action :move_to_signed_in, except: [:index]
  def index
    @itemall = Item.all
  end
  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    #@cart_item.customer_id = current_customer.id
    #@cart_item.item_id = @item.id
  end
  
  private
  
  def move_to_signed_in
    unless customer_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/customers/sign_up'
    end
  end
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/orders_controller.rb
class Publics::OrdersController < ApplicationController
  
  def new
    @order = Order.new
    @customer_address = current_customer.address
    @customer_last_name = current_customer.last_name
    @customer_first_name = current_customer.first_name
  end
  
  def confirm
    #byebug
    @cart_item_all = current_customer.cart_items
    @order = Order.new(order_params)
    @order.shipping_cost = 800
    if params[:order][:select_address] == "0"
      #ご自身の住所を保存する処理
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name+current_customer.first_name
    elsif params[:order][:select_address] == "1"
      #登録済みの住所を保存する処理
      if params[:order][:address_id]
        order = Address.find(params[:order][:address_id])
        @order.postal_code = order.postal_code
        @order.address = order.address
        @order.name = order.name
      else
        flash.now[:danger] = "登録に失敗しました"
        render:new
      end
    elsif params[:order][:select_address] == "2"
      #新規登録住所
      # unless params[:order][:postal_code].blank?#<=本当は[order][:address, :postal_code, name]にしたい ＃追記blankが正しくてもすべて弾く
      # else
      #   render:new
      # end
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    else 
       @customer_last_name = current_customer.last_name
       @customer_first_name = current_customer.first_name
       flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  def top
  end
  
  def create
    #byebug
    @order = Order.new(order_params)
    @order.status = 0
    if @order.save
      @cart_items = current_customer.cart_items
      @cart_items.each do |cart_item|
        @order_detail = OrderDetail.new
        @order_detail.item_id = cart_item.item.id
        @order_detail.price = cart_item.item.with_tax_price
        @order_detail.amount = cart_item.amount
        @order_detail.order_id = @order.id
        @order_detail.save
      end
      @cart_items.destroy_all
      redirect_to orders_top_path
    else
      render:new
    end
  end
  
  def index
    @current_customer_orders = current_customer.orders.all
    #@order_details = order.order_details.new(3)
  end
  
  def show
    #byebug
    @order = Order.find(params[:id])
    @shipping_cost = 800
  end
  
  private
    def order_params
      params.require(:order).permit(:payment_method, :postal_code, :name, :address, :customer_id, :shipping_cost, :total_payment)
    end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end
  
  def after_sign_up_path_for(resource)
    customers_mypage_path
  end
  
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  def after_sign_in_path_for(resource)
   root_path
  end
  


  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/publics/addresses_helper.rb
module Publics::AddressesHelper
end

app/helpers/publics/cart_items_helper.rb
module Publics::CartItemsHelper
end

app/helpers/publics/customers_helper.rb
module Publics::CustomersHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/items_helper.rb
module Publics::ItemsHelper
end

app/views/publics/customers/confirm.html.erb
<div class="row mt-5">
  <div class="col">
    <h4 class="text-center">本当に退会しますか？</h5>
  </div>
</div>

<div class="row mt-5">
  <div class="col">
    <h5 class="text-center">
      退会すると、会員登録情報や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください
    </h5>
  </div>
</div>
<div class="row  justify-content-md-center mt-5">
  <div class="col-2">
    <%= link_to "退会しない", customers_mypage_path, class: "btn btn-block btn-primary" %>
  </div>
  <div class="col-2">
    <%= link_to "退会する", customers_withdrawal_path, class: "btn btn-block btn-danger" %>
  </div>
</div>

app/views/publics/customers/edit.html.erb
<div class="row mt-5">
  <div class="col-auto offset-1 bg-gray">
    <h4 class="mb-0">会員情報編集</h4>
  </div>
</div>

<%= form_with model: @customer, url: customers_customers_infomation_path(@customer), local:true do |f| %>
  <div class="row mt-5">
    <div class="col-3">
      名前
    </div>
    <div class="col-3">
      <%= f.text_field :last_name,class: 'form-control',autofocus: true, autocomplete: "last_name" %>
    </div>
    <div class="col-3">
      <%= f.text_field :first_name,class: 'form-control', autofocus: true, autocomplete: "first_name" %>
    </div>
  </div>
  
  <div class="row mt-2">
    <div class="col-3">
      フリガナ
    </div>
    <div class="col-3">
      <%= f.text_field :last_name_kana, class: 'form-control', autofocus: true, autocomplete: "last_name_kana" %>
    </div>
    <div class="col-3 mr-1">
      <%= f.text_field :first_name_kana,class: 'form-control', autofocus: true, autocomplete: "first_name_kana" %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-3">
      郵便番号(ハイフンなし)
    </div>
    <div class="col-3">
      <%= f.text_field :postal_code,class: 'form-control',autofocus: true, autocomplete: "postal_code" %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-3">
      住所
    </div>
    <div class="col-8">
      <%= f.text_field :address,class: 'form-control',autofocus: true, autocomplete: "address" %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-3">
      電話番号(ハイフンなし)
    </div>
    <div class="col-3">
      <%= f.text_field :telephone_number,class: 'form-control',autofocus: true, autocomplete: "telephone_number" %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-3">
      メールアドレス
    </div>
    <div class="col-3">
      <%= f.text_field :email,class: 'form-control',autofocus: true, autocomplete: "email" %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-3"></div>
    <div class="col-3">
      <%= f.submit "変更内容を保存", class: "btn btn-success btn-block" %>
    </div>
    <div class="col-auto offset-2">
      <%= link_to "退会する", customers_confirm_path, class: "btn btn-danger btn-block" %>
    </div>
  </div>
<% end %>

app/views/publics/customers/show.html.erb
<div class="row mt-5">
  <div class="col-auto offset-1 bg-gray">
    <h4 class="mb-0">マイページ</h4>
  </div>
</div>
<div class="row mt-5">
  <div class="col-auto">
    <h4 class="line-height mt-auto">登録情報</h4>
  </div>
  <div class="col-auto">
    <%= link_to "編集する", customers_information_edit_path, class: "btn btn-success btn-block"%>
  </div>
</div>
<div class="row">
  <div class="col-7">
    <table class="table mt-3 table-bordered border-dark">
      <tr><th class="col-4"> 氏名</th><td><%= @customer.last_name %><%= @customer.first_name %></td></tr>
      <tr><th class="col-4">カナ</th><td><%= @custolast_name_kana %><%= @customer.first_name_kana %></td></tr>
      <tr><th class="col-4">郵便番号</th><td><%= @customer.postal_code %></td></tr>
      <tr><th class="col-4">住所</th><td><%= @customer.address %></td></tr>
      <tr><th class="col-4">電話番号</th><td><%= @customer.telephone_number %></td></tr>
      <tr><th class="col-4">メールアドレス</th><td><%= @customer.email %></td></tr>
    </table>
  <div class="col-5"></div>
  </div>
</div>

<div class="row mt-4">
  <div class="col-2"><h5>配送先</h5></div>
  <div class="col-2">
      <%= link_to "一覧をみる", addresses_path, class: "btn btn-block btn-primary" %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-2"><h5>注文履歴</h5></div>
  <div class="col-2">
    <%= link_to "一覧をみる", orders_path, class: "btn btn-block btn-primary" %>
  </div>
</div>